// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDOloeQ7xAApT9zqy_sPsa8hFiqbigODPA',
    appId: '1:5365175084:android:0f7993e9c570ccf0c51289',
    messagingSenderId: '5365175084',
    projectId: 'crisisconnect-97ed4',
    storageBucket: 'crisisconnect-97ed4.firebasestorage.app',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAtXEQadYphFmIBI_HEliD5oXZJX6ANudM',
    appId: '1:5365175084:web:791cd769a5bc5f82c51289',
    messagingSenderId: '5365175084',
    projectId: 'crisisconnect-97ed4',
    authDomain: 'crisisconnect-97ed4.firebaseapp.com',
    storageBucket: 'crisisconnect-97ed4.firebasestorage.app',
    measurementId: 'G-ZZVY9DZ28E',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCgQYoa5IYb6T4oyCQ7666JtuEs8XXeg-A',
    appId: '1:5365175084:ios:b3c6c42dd7e6fc52c51289',
    messagingSenderId: '5365175084',
    projectId: 'crisisconnect-97ed4',
    storageBucket: 'crisisconnect-97ed4.firebasestorage.app',
    iosBundleId: 'com.example.crisisconnect',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCgQYoa5IYb6T4oyCQ7666JtuEs8XXeg-A',
    appId: '1:5365175084:ios:b3c6c42dd7e6fc52c51289',
    messagingSenderId: '5365175084',
    projectId: 'crisisconnect-97ed4',
    storageBucket: 'crisisconnect-97ed4.firebasestorage.app',
    iosBundleId: 'com.example.crisisconnect',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAtXEQadYphFmIBI_HEliD5oXZJX6ANudM',
    appId: '1:5365175084:web:5d7470319efd5939c51289',
    messagingSenderId: '5365175084',
    projectId: 'crisisconnect-97ed4',
    authDomain: 'crisisconnect-97ed4.firebaseapp.com',
    storageBucket: 'crisisconnect-97ed4.firebasestorage.app',
    measurementId: 'G-24TWW2FJBN',
  );

}